name: Build and deploy from inventage/vanilla-calendar-pro to inventage/vanilla-calendar-pro-dist

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout inventage/vanilla-calendar-pro
        uses: actions/checkout@v4
        with:
          repository: 'inventage/vanilla-calendar-pro'
          path: './vanilla-calendar-pro'
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default token for internal org access

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version you need

      - name: Get package version from vanilla-calendar-pro
        id: get-version
        run: |
          VERSION=$(node -p "require('./vanilla-calendar-pro/package/public/package.json').version")
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Package version is: $VERSION"

      - name: Install dependencies and build
        run: |
          cd ./vanilla-calendar-pro
          npm ci
          npm run package:build

      - name: Checkout Checkout inventage/vanilla-calendar-pro-dist
        uses: actions/checkout@v4
        with:
          repository: 'inventage/vanilla-calendar-pro-dist'
          path: './vanilla-calendar-pro-dist'
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default token for internal org access

      - name: Copy build artifacts
        run: |
          cp -r ./vanilla-calendar-pro/package/dist/* ./vanilla-calendar-pro-dist/
          rm -rf ./vanilla-calendar-pro-dist/.github ./vanilla-calendar-pro-dist/.idea

      - name: Create new branch
        id: create-branch
        run: |
          cd ./vanilla-calendar-pro-dist          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          BRANCH_NAME="release-${{ env.PACKAGE_VERSION }}"
          echo "Creating branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"

      - name: Commit and push changes
        run: |
          cd ./vanilla-calendar-pro-dist
          git add .
          git commit -m "chore: automated build release of version ${{ env.PACKAGE_VERSION }}"
          git push origin "release-${{ env.PACKAGE_VERSION }}"